### ISSUE TITLE
Save and load prifiles

### ISSUE THREAD

**Issue by in4matix** [neuromorph/openbar#10]
Awesome extensions. Working great in Ubuntu 22 with Yaru Shell. How about an option to save and load profiles?

**Comment by neuromorph** [comment]
Thank you :) , happy to hear that.

Yes, saving and loading profiles will make it easier to switch between them. It is on the cards, I will get to it as time permits. 

Maybe, initially an option to Export profile to a file and Import from file will help. Thereby, one can have many profiles saved and load one from them. I'll look into it for next updates.

Thanks for writing, I am keeping this open.

**Comment by in4matix** [comment]
Another potential possibility is to save profiles as themes, then people can create themes and share their themes?

**Comment by neuromorph** [comment]
A new update is live now (v17/v18). It contains options to Export theme-settings to a file and Import theme-settings from a file. This allows to save many themes and import the one desired. The same file can also be shared .
It does not have a mechanism to save all the theme-profiles within the extension (like Custom OSD) and so they can be saved externally as exported files in a local directory.

You can try it out.

**Comment by neuromorph** [comment]
Thanks, there's also options for Auto-theming that you can try out.

That's a great idea about Pling! I will look into it.

**Comment by in4matix** [comment]
Auto-theming works great!! Just using a stock background, after second try it produced a really neat theme (attached). I think Auto-theming should be like the default... The other settings are okay, but a bit too complicated for the average Joe, like me...
![ob1](https://github.com/neuromorph/openbar/assets/62904593/e45fcaf0-4270-4c39-a069-96cc0f9e3af7)
![ob2](https://github.com/neuromorph/openbar/assets/62904593/feb6da3f-8972-4888-b6b6-92da4c676062)
![ob3](https://github.com/neuromorph/openbar/assets/62904593/c8d97fb9-5864-4104-b94b-ca70829d713d)
I went straight to Auto-theming, without even looking at the other settings...
[OB_Auto_Theme_02.zip](https://github.com/neuromorph/openbar/files/14471896/OB_Auto_Theme_02.zip)

**Comment by neuromorph** [comment]
Auto-Theming:
Thank you! You are correct, going through all the settings can be a lot. Auto-theming is an easier option. It can at least get very close to a good theme very quickly and then maybe one or two settings could be tweaked further if one wants. 
I did not make it default since it would have overwritten the settings that people have already configured. Now they have an option to export current settings before trying out auto-theme.

Import/Export:
Before closing the issue, it would be great if you can confirm whether the Exporting theme to a file and later importing the theme (or importing to a new installation) works as expected. 

Thank you for the feedback.

**Comment by in4matix** [comment]
Okay, on a fresh VM, installed OB, imported my saved theme, awesomeness!! (For Gnome 42) 
![Screenshot from 2024-03-03 09-12-37](https://github.com/neuromorph/openbar/assets/62904593/a6943649-9798-4737-b932-ac32c9f3397b)
![Screenshot from 2024-03-03 09-12-59](https://github.com/neuromorph/openbar/assets/62904593/2ec27468-b401-4030-afcb-cdcbac8de516)

**Comment by neuromorph** [comment]
Great! Thanks for verifying.
I am closing the issue.
