### ISSUE TITLE
[MAYBE FEATURE REQ] Colors on wallpaper change might be broken

### ISSUE THREAD

**Issue by Ancairon** [neuromorph/openbar#11]
Hello! Nice extension! Only thing I saw was that when I was going to change wallpaper and selected for foreground color from bg no.2, upon wallpaper change the color would not follow the new generated color, if this is not what is intended, would it be possible to make it like this, so it listens on the wallpaper change and actually update the colors according to the new palette?

Cheers :beers:

**Comment by neuromorph** [comment]
Hello!
At the moment, it auto generates a custom color palette for background and makes it available alongside the default color palette in color selection popups but does not auto apply any colors. So, yes, it would be a feature request. 
I have plans to do that but yet to work out the details and there's also a few other things lined up to add in this extension, stay tuned.
Note: the desktop background color palette would change for each new background/wallpaper in a way that the order of colors may not be very helpful. So the way it could work would be: 
1. Generate color palette for new wallpaper
2. Use some computations over the colors to assign them to FG, BG, highlights, accent etc.
3. Auto apply the assigned colors (as an option). This will update with change of wallpaper.

Of course, the option to manually select and apply any custom colors regardless of wallpaper will remain.
There will additionally be option to export/import settings to/from a file so that one can save the settings profiles and load them back whenever needed.

**Comment by neuromorph** [comment]
Heads up:
The option for auto-theming as per desktop background will be available in the next update.
