### ISSUE TITLE
found another no margin style extension

### ISSUE THREAD

**Issue by swimmingcass** [neuromorph/openbar#14]
os: ubuntu 23.10
executor extension: https://extensions.gnome.org/extension/2932/executor/

![截图 2024-02-24 04-44-02](https://github.com/neuromorph/openbar/assets/146618222/eb1a05d5-5a6c-4442-8d48-db3ef2b31dbe)

**Comment by neuromorph** [comment]
This extension can be installed directly and is available so that's great!
I had a look at their code and they are not creating a Panel Button but instead creating a custom widget :(. 
I will check more details and see if we can have a workaround to apply OpenBar to them. 

Thank you for reporting!

**Comment by neuromorph** [comment]
I checked and yes, the issue is they are not using the standard Gnome Top Panel widgets like Panel Button and Bin. Also, as I suspected, the issue is not about margin but mainly about the vertical padding. (Note: For the Global menu one, please try with zero padding to check that as well.)
Unfortunately, I didn't find a good workaround for it and so the fix needs to go into Executor's code. I installed and made some minor changes to their code and now it seems to work fine. I am attaching the code here so you can try it out. It is for the `extension.js` file of executor extension. You can replace their `extension.js` file with the attached file
[extension.zip](https://github.com/neuromorph/openbar/files/14397471/extension.zip)
.
I will also submit the change to their repo for their consideration since it would help them with compatibility with custom user themes as well.

Let me know. Thanks.

**Comment by neuromorph** [comment]
For completeness and further tracking, here is [the pull request](https://github.com/raujonas/executor/pull/76#issue-2157065262) I submitted to Executor repository. It fixes the issue and also takes steps in the direction they were planning. 
Meanwhile, anyone stumbling here with the same issue, you can use the file from PR linked above.
Thanks.
