### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by Plyply99** [neuromorph/openbar#16]
Greetings!
Love this extension. Are you planning on porting to gnome 46? 
If I change the metadata.json to 46 it somewhat works but is buggy.

Extension manager show this error:
Error: No signal 'actor-added' on object 'StBoxLayout'

Thank you.

**Comment by neuromorph** [comment]
Hello,
Gnome 46 port is now available on Github 'main' branch. I need to do some more tests esp. regression on Gnome 45 and then I will submit for review to extensions web.
Since you seem to be already on Gnome 46, you can download 'main' branch files and replace your local installation to start using it right away. (You will need to log out and log back in after manual install for the new code to take effect.)
If you encounter any bugs or have any suggestions, please report back.

Thanks!

**Comment by Plyply99** [comment]
Trying it now and seems all is well.
You are amazing! That was a fast fix thank you so much.
If I run into any issues I'll be sure to report them.

Thank you again.

**Comment by neuromorph** [comment]
Gnome 46 port is now live on [extensions web store](https://extensions.gnome.org/extension/6580/open-bar/) !
