### ISSUE TITLE
Compatibility with Dash to Panel

### ISSUE THREAD

**Issue by Loup-Garou911XD** [neuromorph/openbar#23]
### Theme doesnt apply to control panel 
![Screenshot from 2024-03-25 19-58-25](https://github.com/neuromorph/openbar/assets/90267658/835f490e-13c6-45ef-8435-868c91d83876)

### although it does apply to other menu panels
![Screenshot from 2024-03-25 19-58-13](https://github.com/neuromorph/openbar/assets/90267658/64f31b4f-14de-461f-8c96-11f6200d222e)

### after turning off and on Dash to Panel it applies correctly
![Screenshot from 2024-03-25 19-58-48](https://github.com/neuromorph/openbar/assets/90267658/c2c80cd2-d735-4da9-bc9c-7682f76308df)

**Comment by neuromorph** [comment]
Interesting! Due to some compatibility quirk, it seems Open Bar needs to enable before Dash to Panel. If the order is reversed, you need to turn Dash to Panel Off and On to get the order right. 
Dash to Panel is a complex extension and I am not sure at the moment what's the cause for this issue. By the way, it is not officially supported by Open Bar for compatibility, yet. Though, it is on cards to be supported along with dock as well. 

I am keeping this open for now. I will update here when I get a chance to figure it out. 

Thank you for reporting!

**Comment by Loup-Garou911XD** [comment]
Also forgot to mention that I am on gnome 46, if that changes anything

**Comment by neuromorph** [comment]
A new update for Open Bar is now live. In that there is an option, under Beyond Bar in settings, for 'Apply menu styles to shell popups'. Turning it On is a way to resolve this issue. That should apply the menu styles to control panel as expected. It will also apply to the the right click menus of the dash apps (in dash-to-panel) or any other shell menus for that matter. 
You should try it out.
