### ISSUE TITLE
How to configure the color of separate lines of menu buttons

### ISSUE THREAD

**Issue by Alan-Kuan** [neuromorph/openbar#25]
As shown in the screenshot, how can I configure the color of these lines?
I tried `Menu > Border Color` and `Menu > Highlight Color`, but neither of them did work.

Are they configurable? Any ideas?

![swappy-20240330-001319](https://github.com/neuromorph/openbar/assets/24734750/db8e11f7-8afa-4107-96b7-424aafaa5f3b)

**Comment by neuromorph** [comment]
Hello,
They are not configurable at the moment. I can look into it to make it work.
However, adding options can make it more complex just for the little tiny lines. This is since, typically, there need to be a color and also alpha for the lines - 1. when the toggle is selected and 2. when the toggle is not selected. There is also case about highlights on hover etc.
Internally setting good defaults can be a simpler way. 
In any case, what would you like the color to be? Same as the selected toggles or not selected ones or foreground/background color?
Let me know.
Thanks.

**Comment by Alan-Kuan** [comment]
Hello.
I tried using GIMP to change the color to the color of the menu background, the color of the line of inactive buttons, and the color of the right part.
I prefer the looking of the first 2.

![Screenshot from 2024-03-29 11-39-25](https://github.com/neuromorph/openbar/assets/24734750/61a64109-f58f-4613-b8e4-1031c05ed5ad)

**Comment by neuromorph** [comment]
OK. I have updated the code in Github. You can get the update by running following command in terminal.

`cd ~/.local/share/gnome-shell/extensions/openbar@neuromorph/; curl -LJO https://raw.githubusercontent.com/neuromorph/openbar/main/stylesheets.js; cd`

I will also include it the next official update.

**Comment by Alan-Kuan** [comment]
Thank you!
It works well, and the menu looks more pleasing now.

![image](https://github.com/neuromorph/openbar/assets/24734750/33ce36ac-32e9-4a66-87b8-566d594dd3bc)

**Comment by neuromorph** [comment]
The update is now live in v28 or v30.
Closing here.
