### ISSUE TITLE
[FEATURE REQUEST] new style on overview

### ISSUE THREAD

**Issue by JE-Amouel** [neuromorph/openbar#36]
Hi
It was only very recently that I discovered the wonderful possibilities that your extension offers,
I appreciate the effort made to provide the user with a simple interface to define a completely customizable style.

I was able to define a style for my desktop when the windows are floating,

![Ubuntu 64-bit-2024-05-31-23-50-15](https://github.com/neuromorph/openbar/assets/146543282/8c44aaae-1f59-4648-a98d-f94667c1a842)

and a different style when the windows are maximized

![Ubuntu 64-bit-2024-05-31-23-42-55](https://github.com/neuromorph/openbar/assets/146543282/d0893b32-e6f9-4e1a-b080-568f7ad18f64)

I would have liked be able to define another style when I am in overview,
I was thinking of a transparent style

Would it be possible to add a new style change event for when we are in overview?

THANKS.

**Comment by neuromorph** [comment]
Hello,

> It was only very recently that I discovered the wonderful possibilities that your extension offers,
I appreciate the effort made to provide the user with a simple interface to define a completely customizable style.

**Comment by neuromorph** [comment]
Hello,

> It was only very recently that I discovered the wonderful possibilities that your extension offers,
I appreciate the effort made to provide the user with a simple interface to define a completely customizable style.

Thank you!

Your desktop does look pretty and clean :+1:  Is that Dash to Panel?

> I would have liked be able to define another style when I am in overview,
I was thinking of a transparent style

Transparent is the best option if you want to change from default style in Overview. Thus, there is a toggle in the settings under Bar Props which says 'Apply in Overview'. Turning it off will remove the style making it transparent. 

I have now changed the way that works (making it transparent instead of removing the styles). Without getting into details, basically it is more efficient now for the next update. However, for some reason or other I never released an interim update that I meant to and now it all will be included in Open Bar 2.0 which is a major update coming soon. I would like to invite you to try it out from GitHub branch 'openbar2.0' (for Gnome 45+, for Gnome 42-44 please refer branch 'g42-44'). This update has new implementation of auto-theming, new settings UI and additional features for applying styles to the entire shell, dock and accent to Gtk/Flatpak apps. It is being discussed in issue #29 by folks already using it.

Thank you!

**Comment by JE-Amouel** [comment]
>Your desktop does look pretty and clean 👍 Is that Dash to Panel?

thank you :smile: 
yes it's dash-to-panel, accompanied by a drink offered by the house (open bar :clinking_glasses: ) .

>I have now changed the way that works (making it transparent instead of removing the styles). Without getting into details, basically it is more efficient now for the next update. However, for some reason or other I never released an interim update that I meant to and now it all will be included in Open Bar 2.0 which is a major update coming soon.

you certainly had good reasons to have waited before providing a major update (sometimes good things take a little while) :wink: , the fact is that the extension has always worked great, it does the job as it should , and it is one of the best extension, and I appreciate the effort made to provide a new user experience accompanied by new functionality, 

> I would like to invite you to try it out from GitHub branch 'openbar2.0' (for Gnome 45+, for Gnome 42-44 please refer branch 'g42-44'). This update has new implementation of auto-theming, new settings UI and additional features for applying styles to the entire shell, dock and accent to Gtk/Flatpak apps. It is being discussed in issue https://github.com/neuromorph/openbar/issues/29 by folks already using it.

wow, it's super cool, I can already imagine how I'll be able to build my own shell theme, it's great.
I will test the extension with pleasure.

**Comment by neuromorph** [comment]
> the fact is that the extension has always worked great, it does the job as it should , and it is one of the best extension, and I appreciate the effort made to provide a new user experience accompanied by new functionality

Thank you, it means a lot!

> I will test the extension with pleasure.

Awesome! 
I noticed some regression on defaults, basically new features to be turned off by default so that users can enable as they wish and to avoid the extension interfering with their existing theming, unless asked.  It is fixed in the latest commit so hope you get that one.

Best!

**Comment by JE-Amouel** [comment]
>I noticed some regression on defaults, basically new features to be turned off by default so that users can enable as they wish and to avoid the extension interfering with their existing theming, unless asked

it's really great, it will add a layer of security in the face of unwanted change, I think that all extensions should act the same way, basically, always ensure that the changes made come from an explicit desire of the user.
It will also allow users to start with a minimal configuration and as they become familiar with the Interface and the functionality, they will be able to build a more advanced style,

really great.

**Comment by neuromorph** [comment]
Closing the issue as completed. 
Thanks!

**Comment by JE-Amouel** [comment]
Thanks to you!
