### ISSUE TITLE
Version 32 of extension ignores any and all changes made in the Top Bar section of Settings

### ISSUE THREAD

**Issue by tledford4** [neuromorph/openbar#41]
Been working fine up until I was prompted to updated to v32 today.  Selecting Islands or Trilands has no effect, nor do any of the other items in the Top Bar section of Settings for the extension.  Disabling/enabling nor logging out have any effect.

$ inxi --system
System:
  Host: P71 Kernel: 6.9.3-3-MANJARO arch: x86_64 bits: 64
  Desktop: GNOME v: 46.2 Distro: Manjaro Linux

Will attempt to drop back to an earlier release until resolved.

Let me know what additional information might assist and I will be happy to provide.

**Comment by neuromorph** [comment]
Hello,

Can you please run the following command in a terminal and then Enable the extension to see if it runs into any error. Please share the trace log if that happens.
`SHELL_DEBUG=all journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

It could also be related to issue #39. That is fixed in GitHub 'main' branch and will be released soon along with another fix for automatically updating the color palette on Dark/Light mode change. You can try it now by downloading the code from 'main' branch and installing manually.

Let me know how it goes.

Thank you for reporting!

**Comment by tledford4** [comment]
Please close this issue and just note me as an insane person.  I went to a timeshift backup and restored what I THOUGHT was an earlier version of the files for the extension, from a backup made on Sunday 6/16, and then noticed that was ALSO version 32 of the extension and that it was behaving as expected.  So the real mysteries are (and are not issues for you but rather for my therapist):

1. Why did GNOME tell me there was an update for the extension when I was ALREADY on the latest release?
2. Why, after I logged out and it "updated" to the release I was already on, did it exhibit the bizarre behavior it did?
3. Why, after I rebooted following the timeshift restore, did v32 work as expected and GNOME said nothing about an update being available for the extension?

:-\

Anyway, thank you for your attention, please disregard, I'm closing this issue and, should I observe more weird behavior, I'll try the debugging step you requested in your comment above and open a new issue.
