### ISSUE TITLE
TypeError:btn.child is undefined

### ISSUE THREAD

**Issue by ms4rkl** [neuromorph/openbar#42]
Got this error since adjusting the settings.
The theming resets to default with each log in and has to be manually activated by importing the profile file while an error icon is still present at the extension list. 

The problem doesn't go away when reverting the settings back to my original setup.
No other extensions have been installed meanwhile.

![Screenshot from 2024-06-21 11-33-25](https://github.com/neuromorph/openbar/assets/93058524/01a7fd7b-07d9-4a04-bc83-60b619fe7859)

(EndeavourOS - 6.9.5-arch1-1 - GNOME 46.2)

**Comment by neuromorph** [comment]
Hello,

What version of Open Bar are you on? Can you please try with the latest version 33.

If already on latest, please run the following command in a terminal and then Enable the extension. If the error is preventing the extension from enabling then just remove and install the extension again while the command is running. If there is no error during enable then keep the command running and try disabling the extension. At some point the same error will show up in the terminal but it will also have a trace log. Please share that here so we can debug the issue. 

`SHELL_DEBUG=all journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

> The theming resets to default with each log in and has to be manually activated by importing the profile file while an error icon is still present at the extension list.

This is likely also happening because of the above error. So, test it again after that error is fixed and let me know if the issue persists.

Thanks for reporting!

**Comment by ms4rkl** [comment]
Version: *already 33*

The output:
```
Source ID 31616 was not found when attempting to remove it
Extension openbar@neuromorph: TypeError: btn.child is undefined

Stack trace:
  enable@file:///home/misa/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:1095:20
  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:266:38
  async*_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:626:24
  _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:731:18
  createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
  enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:289:29
  _onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:327:40
  async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:134:41
  @resource:///org/gnome/shell/ui/init.js:21:20
```
(When enabled after reinstall, no ouput on disable)

**Comment by neuromorph** [comment]
I have added a fix for the error in GitHub. You get it by running the following command (you need curl installed). It downloads the `extension.js` file from 'main' branch and replaces local file. You can also do that manually if you like.

`cd ~/.local/share/gnome-shell/extensions/openbar@neuromorph/; curl -LJO https://raw.githubusercontent.com/neuromorph/openbar/main/extension.js; cd`

You need to logout/login after doing that for the changes to take effect.

Let me know how it goes.

Thanks.

**Comment by ms4rkl** [comment]
Unfortunatelly this hasn't fixed it for me. It has made no difference.

**Comment by NathanKhoP** [comment]
i tried downloading the `extension.js` file as requested, but the error still persists (i curled like 4 times now)

**Comment by neuromorph** [comment]
@NathanKhoP 
> i tried downloading the extension.js file as requested, but the error still persists (i curled like 4 times now)

I hope you are on Gnome 45+, this only applies to that. For Gnome 42-44, you will need to refer to 'g42-44' branch instead of 'main'.
Other than that, key is to log out and login again after replacing the file, as also highlighted by @ms4rkl above. If you are having any trouble with the `curl` command, you can manually download the file from GitHub and replace local `extension.js` with downloaded file.
The local install path, as also seen in the command above, is: `~/.local/share/gnome-shell/extensions/openbar@neuromorph/`

Let me know how it goes. The fixes will be in the upcoming update very soon (depending on Gnome review timeframe).

**Comment by NathanKhoP** [comment]
the issue was the curl command, so i renamed 'extension.js' and now im met with another error, saying "import declarations may only appear at top level of a module"
![image](https://github.com/neuromorph/openbar/assets/161797293/3eec7fff-6345-4df7-9568-8b0396d0c4a1)

**Comment by neuromorph** [comment]
@NathanKhoP 

The error is saying that you have the file from incorrect branch for your Gnome version, like I said:
> I hope you are on Gnome 45+, this only applies to that. For Gnome 42-44, you will need to refer to 'g42-44' branch instead of 'main'.

On the other hand, the new version with all the fixes is already live now. So, all you have to do is uninstall and install latest version again from Gnome extensions website or Extension Manager app.
