### ISSUE TITLE
[BUG]: "Apply Accent to Shell allover" and not "Apply All to Shell allover" cause app icon highlights to disappear in shell overview

### ISSUE THREAD

**Issue by mkalinski** [neuromorph/openbar#50]
**Describe the bug** 
When the Gnome Shell setting "Apply Accent to Shell allover" is on, and "Apply All to Shell allover" is off, highlights that appear when the cursor moves over app icons in overview are not visible.

**To Reproduce**
- Turn "Apply Accent to Shell allover" on.
- Turn "Apply All to Shell allover" off.
- Press the "super" key twice to enter the view where the effect is the easiest to notice.
- Mouse over any app icon.
- No highlight is visible, when it normally is.

**Relevant  Specs:**
 - Open Bar version: git, main branch
 - Gnome version: 46
 - OS/Distribution: Fedora 40

**Screenshots**
![image](https://github.com/neuromorph/openbar/assets/959502/43f7c9e1-fee9-417c-b9d6-29d6472953dd)
Highlight normally visible.

![image](https://github.com/neuromorph/openbar/assets/959502/b7be4705-b2d1-47ca-b942-d48fbd7c0a1d)
Highlight not visible because of the bug.

**Comment by neuromorph** [comment]
Bug fix added to `main`.

Thanks for reporting!

Let me know.

**Comment by mkalinski** [comment]
Looks fixed, thanks.

Sorry for the delay on checking this one. :stuck_out_tongue:

**Comment by neuromorph** [comment]
Thank you for informing!

There has been a few core updates and they are now merged into `main` branch so you may want to pull latest.
- Installation for immutable OS like NixOS through their packaging system was failing since the install space is read-only and does not allow editing stylesheet. Thus, the stylesheet and few SVG icons are moved into run-time directory and would work from there. The change will be applied for all distributions (immutable or not).
- The writes were already using some callbacks but more explicit async Gio/GLib routines are now employed
- Bar BG color is set to transparent when bartype is auto changed to Tri/islands.
- Fixes for highlights 

Let me know if you face any issues on the latest commit.

**Comment by neuromorph** [comment]
New version of Open Bar with the fix is live on Gnome extensions, closing here.
