### ISSUE TITLE
New feature : handle multiple monitors

### ISSUE THREAD

**Issue by Hidigoudi** [neuromorph/openbar#54]
Sorry if I don't respect correctly the contribute rules as there is no "new feature" or "suggestion" template.

I have just installed this gnome extension on my Debian Sid and it works perfectly. However I do not see anywhere in the settings the possibility to display the top bar on my second monitor. 

Is it possible to add this feature in a future version ?

Thanks !

**Comment by neuromorph** [comment]
> Sorry if I don't respect correctly the contribute rules as there is no "new feature" or "suggestion" template.

No worries. I will put out a template at some point. Thank you for your suggestion!

Currently, Open Bar does not set the monitor for the Top Bar, only tries to retain it wherever it is. There is an extension called Fullscreen Avoider which moves the Bar to other monitor if a window goes fullscreen and is about to hide the bar. Open Bar is made compatible with it since some users had requested.

To have the top bar on multi-monitors is certainly useful. There is an [open issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4603) in Gnome for the same if you would like to track. 

For now, I just searched for available options and came across [this extension](https://github.com/lazanet/multi-monitors-add-on) which might be helpful but I haven't tried it. 
Maybe you can try it out and let me know how it goes.

**Comment by Hidigoudi** [comment]
Thank you for your suggestions !

For now I tested the Fullscreen Avoider extension but it does not seems to work as expected in my environment :
![image](https://github.com/neuromorph/openbar/assets/173546307/ffe71040-4e59-4d08-badd-341eca060147)

I'm using Debian Sid with Gnome + X11. The top bar does not hide when I have a full screen window.

Unfortunately the multi-monitors-add-on is not compatible with my Gnome version :(

**Comment by neuromorph** [comment]
> For now I tested the Fullscreen Avoider extension but it does not seems to work as expected in my environment :
I'm using Debian Sid with Gnome + X11. The top bar does not hide when I have a full screen window.

Are you saying by default the Top bar does not hide on full screen in your setup? That's unexpected. Maximizing a window will not hide it but full screen should - just to clarify. Though it may not be what you are looking for.

> Unfortunately the multi-monitors-add-on is not compatible with my Gnome version :(

This extension maybe more in line with your requirement. On their GitHub link, shared earlier, they have separate versions of their extension for different Gnome versions from Gnome 3.xx to 46. For your case, it will be the `gnome-42_44` branch version. It seems you will need to do manual install from GitHub.

**Comment by neuromorph** [comment]
While the issue is 'closed', I am curious to know how it went :)
Were you able to get it to work using that extension? Were there any compatibility issues?

This seems like something many people would be interested in, so it may help them as well when they stumble here.
Thanks.

**Comment by Hidigoudi** [comment]
I managed to use an extension that hides the top bar when a window is in full screen. However I'm not able to put the customized top bar on my second screen. It is fine for me as it was annoying to always get this top bar when with a full screen app.

**Comment by Hidigoudi** [comment]
NEWS : Gnome 46 was released yesterday on Debian Unstable and the Fullscreen Avoider extension now works correctly.
