### ISSUE TITLE
[BUG]: TypeError: btns[k].child is undefined.

### ISSUE THREAD

**Issue by oRodriigo** [neuromorph/openbar#62]
**Describe the bug**
Open Bar is not working. I already tried to reinstall the extension, either via Gnome-Shell website or downloading .zip file and installing it manually, but no fixes. It just don't customize my top bar. Already tried to fix by the guide: https://github.com/neuromorph/openbar/issues/61 
but no fix as well.
**To Reproduce**
Just started OS and my customized top bar just didn't appeared. 
**Relevant  Specs:**
 - Open Bar version: 37
 - Gnome version:  46
 - OS/Distribution: Arch Linux
 - Other installed extensions if interference is expected [Optional]: 

**Screenshots**

![image](https://github.com/user-attachments/assets/6c24089e-5087-41e9-8222-55cc0bffab6e)

**Error Stack Trace**
Can't update stage views actor bms-dash-backgroundgroup [MetaBackgroundGroup] is on because it needs an allocation.
Can't update stage views actor bms-dash-blurred-widget [StWidget] is on because it needs an allocation.
Can't update stage views actor dashtodockContainer [Gjs_dash-to-dock_micxgx_gmail_com_docking_DashToDock] is on because it needs an allocation.
Can't update stage views actor unnamed [Gjs_dash-to-dock_micxgx_gmail_com_docking_DashSlideContainer] is on because it needs an allocation.
Can't update stage views actor dashtodockBox [StBoxLayout] is on because it needs an allocation.

**Comment by neuromorph** [comment]
Hello,

I have added another fix, something was amiss. This should fix both #61 and #62. Please try again from GitHub main branch or using the same command given in #61. 
One more thing, the zip from main had previous version number in `metadata.json` and so it will get overwritten with the version from Gnome extensions website. So, in case you downloaded zip and using it, change the version in that file to 37 OR just redownload the zip since I have fixed it in GitHub.

You will need to log out and log in after the new update. 

Let me know if it works or if the issue persists.

Thank you for reporting!

**Comment by oRodriigo** [comment]
It works! Thanks for fixing it!

**Comment by neuromorph** [comment]
A new version v38 with the fix has been released, closing this.
