### ISSUE TITLE
[BUG]:"obj is undefined" error 

### ISSUE THREAD

**Issue by AnAxeCalledNegus** [neuromorph/openbar#70]
Obj is undefined shows up in the extension manager , I can't enable nor disable openbar too .
![Screenshot from 2024-09-07 18-55-25](https://github.com/user-attachments/assets/ba265ade-cf64-4b8b-83a5-cd683e0b7e77)

**Comment by neuromorph** [comment]
Hello,

Please use the Bug Report template when logging a bug so that relevant info can be captured.
I see Open Bar version 34, please also provide the Gnome version and your OS/distribution, in case it may help.

For the error, you need to get a stack trace as mentioned in the Bug template. Copying the process below for quick reference:

**Error Stack Trace**
If you are getting an error (showing in the Extension Manager for e.g.), please run the following command in a terminal and then Enable the extension. If the error is preventing the extension from enabling then first remove/uninstall the extension then run the below command in a terminal and again install the extension while the command is running. If there is no error during enable then keep the command running and try disabling the extension. At some point the same error will show up in the terminal but it will also have a trace log. Please share that here so we can debug the issue.
`SHELL_DEBUG=all journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

Thank you for reporting!

**Comment by AnAxeCalledNegus** [comment]
Hi,
My machine is running Ubuntu 22.04 with GNOME 42.9 , I tried every method of error stack tracing but it was always the same series of logging , Also the extension never got enabled even after a reinstall,
Here's what pops up : 
JS ERROR: Extension openbar@neuromorph: TypeError: obj is undefined
connect@/home/o/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:49:13
applyMenuStyles@/home/o/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:415:47
enable@/home/o/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:1151:14

**Comment by neuromorph** [comment]
Thanks, this log shows the files/lines where issue is occurring. It seems to do with the Notifications section shown when you click on the Date button in the panel. It is complaining that the section-list for messages is 'undefined'.

- Are you using any extensions that modify the Notifications menu? If so which ones?
- Please post a screenshot of the top panel with the Date/Notifications menu open so we can see the details.

**Comment by AnAxeCalledNegus** [comment]
After some testing , I concluded that an extension called "Just perfection" is interfering with openbar for some reason , disabling it fixes the issue .
I'll post a picture regarding the top panel but It probably won't be helpful , my top panel is modified a bit much .
![image](https://github.com/user-attachments/assets/e6c5f77d-8d71-4b04-b85c-f28cc6030a43)

**Comment by AnAxeCalledNegus** [comment]
I'm using an extension called "Big Sur status area" for it to be spread out like this


> After some testing , I concluded that an extension called "Just perfection" is interfering with openbar for some reason , disabling it fixes the issue . I'll post a picture regarding the top panel but It probably won't be helpful , my top panel is modified a bit much . ![image](https://private-user-images.githubusercontent.com/180770799/365423250-e6c5f77d-8d71-4b04-b85c-f28cc6030a43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODMyNDksIm5iZiI6MTcyNTc4Mjk0OSwicGF0aCI6Ii8xODA3NzA3OTkvMzY1NDIzMjUwLWU2YzVmNzdkLThkNzEtNGIwNC1iODVjLWYyOGNjNjAzMGE0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwODA5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmRiMTI1MmFiNDE5NGE5NTAyMTZlOGVhYTI0Mzc1ZjBhNGEyY2NjODM5NTM5YTJhNTQ2NjFmOWExNWU5YTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Iy7tos8IVn-S_CmgZFmrXIHD9nlqdlcxJDU-JVCjWAI)

**Comment by AnAxeCalledNegus** [comment]
It's fixed now , 
Customization options related to notifications and clock positions were incorrectly set.
Thank you very much for assisting me !

**Comment by neuromorph** [comment]
> After some testing , I concluded that an extension called "Just perfection" is interfering with openbar for some reason , disabling it fixes the issue .

Glad that it worked for you! However, I am not sure how "Just Perfection" is interfering. On the other hand, the "Big Sur status area" extension seems to be changing the placement of message section-list from Date menu so that could be the reason for the error.

As I was typing, I just saw this update from you:
> It's fixed now ,
Customization options related to notifications and clock positions were incorrectly set.

Well, that's great to know. :+1:  
I am also looking into a future update to openbar where it should depend less on other extensions.

> Thank you very much for assisting me !

You are welcome!

**Comment by AnAxeCalledNegus** [comment]
> > After some testing , I concluded that an extension called "Just perfection" is interfering with openbar for some reason , disabling it fixes the issue .
> 
> Glad that it worked for you! However, I am not sure how "Just Perfection" is interfering. On the other hand, the "Big Sur status area" extension seems to be changing the placement of message section-list from Date menu so that could be the reason for the error.
> 
> As I was typing, I just saw this update from you:
> 
> > It's fixed now ,
> > Customization options related to notifications and clock positions were incorrectly set.
> 
> Well, that's great to know. 👍 I am also looking into a future update to openbar where it should depend less on other extensions.
> That would be amazing !
> > Thank you very much for assisting me !
> 
> You are welcome!

**Comment by AnAxeCalledNegus** [comment]
Openbar is already amazing ,an update like you said would be the cherry on top !
