### ISSUE TITLE
[BUG]: UI issue on activated "do not disturb" on notification center

### ISSUE THREAD

**Issue by kauanmocelin** [neuromorph/openbar#71]
**Describe the bug**
When activated "do not disturb" toggle, on notification center, the bell is overwrite by islands border

**To Reproduce**
Activate "do not disturb" toggle, on notification center

**Relevant  Specs:**
 - Open Bar version:  38
 - Gnome version: GNOME 46.0
 - OS/Distribution: Ubuntu 24.04.1 LTS x86_64
 - Other installed extensions if interference is expected [Optional]: User Themes

**Screenshots**
![Screenshot from 2024-09-09 11-52-42](https://github.com/user-attachments/assets/f56fbf40-032c-4437-bd35-73b5123cb079)

**Comment by neuromorph** [comment]
Hello,

It is not expected since the button expands when DND is turned On as per default Gnome behavior. 
How did you get the weather there, an extension? What extension are you using for that and what User theme as well? I will try to reproduce if possible.

I haven not faced it on same setup Ubuntu 24.04 so it is being caused by some customization like User theme or the added weather info maybe though not expected. 

Thanks for reporting!

**Comment by kauanmocelin** [comment]
The problems is with theme, after disable "User Themes" openbar it works as expected.

**Comment by neuromorph** [comment]
Thank you for the update!
