### ISSUE TITLE
[BUG]: tri/island alpha set to zero has no effect for the middle part of the triland.

### ISSUE THREAD

**Issue by xcpky** [neuromorph/openbar#76]
**Describe the bug**
tri/island alpha set to zero has no effect for the middle part of the island.
that is, only the round part of the island is completely transparent.
**To Reproduce**
1. set tri/island alpha to zero
**Relevant  Specs:**
 - Open Bar version: 41
 - Gnome version: 41
 - OS/Distribution: archlinux
 - Other installed extensions if interference is expected [Optional]: 

**Screenshots**
![Screenshot From 2024-09-29 17-51-15](https://github.com/user-attachments/assets/c07f95f1-c472-43a7-a123-0bbe3056e516)

Also, I find the tri/island alpha is not continous. For example, setting it as 0.01 has the same effect of setting it as 0.1

**Comment by neuromorph** [comment]
Hello,

> tri/island alpha set to zero has no effect for the middle part of the island.

You have kept the "Neon Glow" On under "Bar Border" tab. It requires the BG to be relatively opaque since it is a shadow effect. What you see in the middle is the shadow that is usually hidden behind the widget. To get the transparent effect i.e. for zero or near zero alpha, you should turn Off "Neon Glow".

> Also, I find the tri/island alpha is not continous. For example, setting it as 0.01 has the same effect of setting it as 0.1

While the change from 0.01 to 0.1 would be subtle, in this case it maybe getting masked by the shadow again, so turn off Neon and then try.

One more thing, what extension are you using for the weather? The Sun icon looks black/dark while the FG text is white. When I tested with "Weather O'Clock" extension, the icon is also white. Sometimes, the icon has its own color and is not colorable through css.

Thanks for reporting!

**Comment by neuromorph** [comment]
> all the icon is black while the font is white.

That is unexpected. All the black icons should also be white i.e. same color as font. It is tested on Gnome 47 as well (I believe you meant 47 and not 41).
Are you using any User Theme/Shell Theme? I am not able to reproduce it like your screenshot.
Maybe you can try by turning off Auto FG for Bar and manually selecting the FG Color as White.

**Comment by xcpky** [comment]
> It is tested on Gnome 47 as well (I believe you meant 47 and not 41).
yes I mean gnome 47, I confused it with fedora 41, sorry.
> Are you using any User Theme/Shell Theme?
I think no, the only theme i am using is adw-gtk3, but that's for lagacy apps.
> Maybe you can try by turning off Auto FG for Bar and manually selecting the FG Color as White.
Yes that's what I am currently doing now. Maybe I should open another issue.
