### ISSUE TITLE
The battery indicator in the top-right corner menu is of different background

### ISSUE THREAD

**Issue by vvswps** [neuromorph/openbar#8]
Since the battery percentage indicator is a button as well shouldn't it be governed by the same styles as the other buttons

It appears different from other buttons

I tried to fish around in the css file but couldn't find the cause

[Screencast from 2024-01-19 01-27-49.webm](https://github.com/neuromorph/openbar/assets/20621664/634430a6-322d-4063-9352-b107698cbd4a)

**Comment by neuromorph** [comment]
Hello,
Yes, it should also have consistent styling. However, it is not a standard element in Gnome so I believe you are using some extension to add that indicator. Extensions, adding widgets to the panel, many times do not use the default Gnome layout/styling and make something custom which may not be captured by Open Bar. Please comment which extension you are using for the battery indicator and I will look into it for making it compatible.

Also, the screen recorder button looks taller than the Settings button which could be a bug so I will look into that as well.

Thanks for reporting!

**Comment by vvswps** [comment]
Hey, I'm really sorry I couldn't identify what extension was adding that indicator, I even tried turning off all the extensions but to no avail.

I had installed Xfce a while back and then purged it...maybe some element remained from that.

As for the screen recorder button, I thought the design was intentional to draw attention to the fact that it's recording.
Maybe you can give it a different style but that's for you to decide I'm no expert in UX.

Thanks for making this extension and suggesting this vibrant pink/purple bg

**Comment by neuromorph** [comment]
I missed to mention, if not an extension then it is probably a custom user theme. For e.g. Marble Shell theme does something very similar here (but not exactly same):
https://images.pling.com/img/00/00/70/02/69/1977647/qs4.png
Let me know the theme, if that is the case and I will check the theme element and try to fix the battery style.

I looked into the recorder button and Gnome does handle it a bit differently including red background that was missed here. The size is bigger since padding was not applied to it due to the differences. I had the same thought when testing that the bigger size is indeed useful to grab attention and to click 'Stop'. I decided to let it be bigger (zero padding) and also added the red background as per default Gnome style. It will reflect in next update. 

Next update will have a few fixes and some additions soon. Hope to also fix the battery button in that.

> Thanks for making this extension and suggesting this vibrant pink/purple bg

You are welcome!

**Comment by neuromorph** [comment]
Update:
About battery indicator:
I did some search and it seems Gnome did have it or there is some way to enable it, I am not sure yet. I tested in VM for Fedora 38 and 39 but they don't show it by default. I will look further, meanwhile this is a heads up that I might have been wrong above.

**Comment by neuromorph** [comment]
OK, I found the problem why the battery indicator wasn't available in my test boxes. It is since Boxes app does not detect/expose the battery. I thus installed Virtual Box and created a VM for Fedora 39 1.5. 
I was able to reproduce the issue and I have fixed it. It will be available in next update. Meanwhile, I may create a quick patch for you to try so you can fix it before the update.
[QuickSettBatteryIndicator.webm](https://github.com/neuromorph/openbar/assets/4656768/5f0d2264-206c-4966-b55e-c18a48c50e41)

Stay tuned.

**Comment by vvswps** [comment]
Oh wow you really went after that lil indicator. I'm curious though what was the bug? Is the indicator a different button or object that you weren't targeting previously or was it something else?

**Comment by neuromorph** [comment]
Yes, it needed fixing :)
Gnome boxes did not show that indicator so I missed it. Others in that row are icon-buttons but this one isn't.

You can try out by patching using following command. After running the command, you need to logout and login to refresh Gnome/extension. Also, after that open the Open Bar settings window and click on 'Apply Menu Styles' under MENUS.

`cd ~/.local/share/gnome-shell/extensions/openbar@neuromorph/; curl -LJO https://raw.githubusercontent.com/neuromorph/openbar/main/prefs_quickBatteryPatch.js; cat prefs_quickBatteryPatch.js > prefs.js; rm prefs_quickBatteryPatch.js; cd`

**Comment by vvswps** [comment]
Hey, sorry for ghosting...the new update fixes the battery icon issue. Thanks a lot!
