### ISSUE TITLE
[BUG]: bug with gnordvpn-local extension when islands mode active

### ISSUE THREAD

**Issue by paolocalosso** [neuromorph/openbar#94]
**Describe the bug**
i love open bar gnome extension! i also use gnordvpn-local extension to manage my nordvpn connections but it doesn't seem to respect the top bar margin as shown in the attached screenshot

**To Reproduce**
1. install open bar extension and set top bar type to islands mode
2. install gnordvpn-local extension
3. the gnordvpn-local icon borders in top bar seem "bigger" than expected

**Relevant  Specs:**
 - Open Bar version: 41
 - Gnome version: 47
 - OS/Distribution: ubuntu 24.04 and debian sid
 - Other installed extensions if interference is expected [Optional]: [gnordvpn-local ](https://github.com/Isopolito/gNordVPN-Local)

**Screenshots**
![Screenshot from 2024-12-12 18-13-45](https://github.com/user-attachments/assets/f268e6a4-fb1e-4dd7-8478-cb75369de4bc)

**Comment by neuromorph** [comment]
Hello,

This happens when something is off in the way the other extension adds an indicator/panel_button to the panel.
I looked into the code of gnordvpn-local and it seemed that they are creating and adding the indicator just fine. After some digging I saw one place where it is a bit amiss. I suggest you try this change in their code and see if it works for you.
Go to installation directory of gnordvpn and within that open `modules` directory. Then open the file `VpnIndicator.js`.
To the end of that file, you will find this function `_moveIndicator`. Replace that with the code below. [The original code missed on the container part].
```
_moveIndicator() {
            let position = this._extSettings.get_string(`panel-position`);

            let box;
            if (position === `left`) box = Main.panel._leftBox;
            else if (position === `center`) box = Main.panel._centerBox;
            else box = Main.panel._rightBox;

            // Remove the indicator from its current parent
            let container = this.container;
            container.show();

            let parent = container.get_parent();
            if (parent)
                parent.remove_child(container);

            // Add it to the new box using the updated method
            box.add_child(container);
        }
```

Then save and close it. You will need to log out and login for changes to reflect.
In the settings of this extension, there is a section for Styles which has `Common CSS` line with some border/padding/margin styles. You can further adjust or remove it as needed.

Let me know if that code works for you then I will request them to update it gnordvpn itself.

Cool bar by the way :)

**Comment by paolocalosso** [comment]
your code works perfectly! 
![Screenshot from 2024-12-16 11-30-30](https://github.com/user-attachments/assets/3de12e3f-aa54-4283-b681-689f807d6414)
your extension is absolutely the best one  inside the entire gnome!

**Comment by Isopolito** [comment]
@neuromorph, 

thanks for that code fix, much appreciated :heart:
